/**
 * ALNAV Messages Data
 *
 * Auto-generated from MyNavyHR Website
 * Source: https://www.mynavyhr.navy.mil/References/Messages/ALNAV-{YEAR}/
 * Years Fetched: 2023-2025 (2025, 2024, 2023)
 * Generated: 2025-11-16T21:17:42.813Z
 * Total Records: 0
 *
 * This file is automatically generated by scripts/fetch-alnav.mjs
 * Fetches from current year and previous 2 years dynamically
 * DO NOT EDIT MANUALLY
 */

// ALNAV messages data structure
const ALNAV_MESSAGES = [];

// Metadata
const ALNAV_META = {
  sourceUrls: ['https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2025/', 'https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2024/', 'https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2023/'],
  yearsFetched: [2025, 2024, 2023],
  yearRange: '2023-2025',
  generatedAt: '2025-11-16T21:17:42.813Z',
  totalRecords: 0
};

// Export for use in application
if (typeof window !== 'undefined') {
  window.ALNAV_MESSAGES = ALNAV_MESSAGES;
  window.ALNAV_META = ALNAV_META;
}

// Also support module exports for testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    ALNAV_MESSAGES,
    ALNAV_META
  };
}
