/**
 * ALNAV Messages Data
 *
 * Auto-generated from MyNavyHR Website
 * Source: https://www.mynavyhr.navy.mil/References/Messages/
 * Generated: 2025-11-13T06:32:36.236Z
 * Total Records: 2
 *
 * This file is automatically generated by scripts/fetch-alnav.mjs
 * DO NOT EDIT MANUALLY
 */

// ALNAV messages data structure
const ALNAV_MESSAGES = [
  {
    "id": "ALNAV 023/25",
    "title": "IMPLEMENTATION OF ALNAV 023/25",
    "subject": "IMPLEMENTATION OF",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25025.pdf?ver=jmcIyqqBOmBxd9bB6HiCBA%3d%3d",
    "pubDate": "2025-01-01T00:00:00.000Z",
    "description": ""
  },
  {
    "id": "ALNAV 021/24",
    "title": "CANCELLATION OF ALNAV 021/24",
    "subject": "CANCELLATION OF",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24022.txt?ver=zQUPD1-UMQys8xJP48r9uA%3d%3d",
    "pubDate": "2024-01-01T00:00:00.000Z",
    "description": ""
  }
];

// Metadata
const ALNAV_META = {
  sourceUrl: 'https://www.mynavyhr.navy.mil/References/Messages/',
  generatedAt: '2025-11-13T06:32:36.236Z',
  totalRecords: 2,
  lastUpdate: '2025-11-13T06:32:36.236Z'
};

// Export for use in application
if (typeof window !== 'undefined') {
  window.ALNAV_MESSAGES = ALNAV_MESSAGES;
  window.ALNAV_META = ALNAV_META;
}

// Also support module exports for testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    ALNAV_MESSAGES,
    ALNAV_META
  };
}
