/**
 * ALNAV Messages Data
 *
 * Auto-generated from MyNavyHR Website
 * Source: https://www.mynavyhr.navy.mil/References/Messages/ALNAV-{YEAR}/
 * Years Fetched: 2023-2025 (2025, 2024, 2023)
 * Generated: 2025-11-13T06:00:00.000Z
 * Total Records: 6
 *
 * This file is automatically generated by scripts/fetch-alnav.mjs
 * Fetches from current year and previous 2 years dynamically
 * NOTE: Contains sample data for testing - run npm run fetch-alnav to update with live data
 * DO NOT EDIT MANUALLY
 */

// ALNAV messages data structure
const ALNAV_MESSAGES = [
  {
    "id": "ALNAV 003/25",
    "title": "ALNAV 003/25 - FY-25 Navy Reserve Officer Continuation and Voluntary Early Retirement",
    "subject": "FY-25 Navy Reserve Officer Continuation and Voluntary Early Retirement",
    "link": "https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2025/ALNAV-003-25/",
    "pubDate": "2025-01-15T00:00:00.000Z",
    "description": ""
  },
  {
    "id": "ALNAV 002/25",
    "title": "ALNAV 002/25 - FY-25 Navy Tuition Assistance Update",
    "subject": "FY-25 Navy Tuition Assistance Update",
    "link": "https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2025/ALNAV-002-25/",
    "pubDate": "2025-01-10T00:00:00.000Z",
    "description": ""
  },
  {
    "id": "ALNAV 082/24",
    "title": "ALNAV 082/24 - FY-25 Navy Active-Duty and Reserve E-7 Selection Board Results",
    "subject": "FY-25 Navy Active-Duty and Reserve E-7 Selection Board Results",
    "link": "https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2024/ALNAV-082-24/",
    "pubDate": "2024-10-01T00:00:00.000Z",
    "description": ""
  },
  {
    "id": "ALNAV 056/24",
    "title": "ALNAV 056/24 - FY-25 Navy Reserve Officer Promotion Selection Board Results",
    "subject": "FY-25 Navy Reserve Officer Promotion Selection Board Results",
    "link": "https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2024/ALNAV-056-24/",
    "pubDate": "2024-07-15T00:00:00.000Z",
    "description": ""
  },
  {
    "id": "ALNAV 089/23",
    "title": "ALNAV 089/23 - FY-24 Navy Enlisted Advancement Results",
    "subject": "FY-24 Navy Enlisted Advancement Results",
    "link": "https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2023/ALNAV-089-23/",
    "pubDate": "2023-11-20T00:00:00.000Z",
    "description": ""
  },
  {
    "id": "ALNAV 045/23",
    "title": "ALNAV 045/23 - FY-24 Active Duty Officer Promotion Selection Board Results",
    "subject": "FY-24 Active Duty Officer Promotion Selection Board Results",
    "link": "https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2023/ALNAV-045-23/",
    "pubDate": "2023-06-30T00:00:00.000Z",
    "description": ""
  }
];

// Metadata
const ALNAV_META = {
  sourceUrls: ['https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2025/', 'https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2024/', 'https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2023/'],
  yearsFetched: [2025, 2024, 2023],
  yearRange: '2023-2025',
  generatedAt: '2025-11-13T06:00:00.000Z',
  totalRecords: 6,
  note: 'Sample data for testing - run npm run fetch-alnav to update with live data'
};

// Export for use in application
if (typeof window !== 'undefined') {
  window.ALNAV_MESSAGES = ALNAV_MESSAGES;
  window.ALNAV_META = ALNAV_META;
}

// Also support module exports for testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    ALNAV_MESSAGES,
    ALNAV_META
  };
}
