/**
 * SECNAV Directives Data
 *
 * Auto-generated from SECNAV RSS Feed
 * Source: https://rss.app/feeds/gtjRe8dzN4BUYIrV.xml
 * Generated: 2025-11-13T06:14:52.928Z
 * Total Records: 1
 *
 * This file is automatically generated by scripts/fetch-secnav.mjs
 * DO NOT EDIT MANUALLY
 */

// SECNAV directives data structure
const SECNAV_DIRECTIVES = [
  {
    "id": "[Action required] Your RSS.app Trial has Expired.",
    "title": "[Action required] Your RSS.app Trial has Expired.",
    "subject": "[Action required] Your RSS.app Trial has Expired.",
    "link": "https://rss.app",
    "pubDate": "Thu, 13 Nov 2025 06:14:52 GMT",
    "description": "Your trial has expired. Please update your subscription plan at <a href=\"https://rss.app\">rss.app</a>. - (gtjRe8dzN4BUYIrV)"
  }
];

// Metadata
const SECNAV_META = {
  sourceUrl: 'https://rss.app/feeds/gtjRe8dzN4BUYIrV.xml',
  generatedAt: '2025-11-13T06:14:52.928Z',
  totalRecords: 1,
  lastUpdate: '2025-11-13T06:14:52.928Z'
};

// Export for use in application
if (typeof window !== 'undefined') {
  window.SECNAV_DIRECTIVES = SECNAV_DIRECTIVES;
  window.SECNAV_META = SECNAV_META;
}

// Also support module exports for testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    SECNAV_DIRECTIVES,
    SECNAV_META
  };
}
