/**
 * SECNAV Directives Data
 *
 * Real SECNAV instructions from DONI (Department of the Navy Issuances)
 * Source: https://www.secnav.navy.mil/doni/Directives/Forms/doniAllInstructions.aspx
 * Generated: 2025-12-22T07:48:39.870Z
 * Total Records: 53
 *
 * URL Pattern:
 * https://www.secnav.navy.mil/doni/Directives/{category}/{subcategory}/{instruction}.pdf
 *
 * This file is automatically generated by scripts/generate-secnav-data.mjs
 * DO NOT EDIT MANUALLY
 */

// SECNAV directives data structure
const SECNAV_DIRECTIVES = [
  {
    "id": "SECNAVINST 12271.1",
    "title": "SECNAVINST 12271.1 - TELEWORK PROGRAM",
    "subject": "TELEWORK PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/12000%20Civilian%20Personnel/12-02%20Employee%20Programs/12271.1.pdf",
    "pubDate": "2022-04-20T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 12271.1 - TELEWORK PROGRAM",
    "category": "Civilian Personnel",
    "effectiveDate": "2022-04-20"
  },
  {
    "id": "SECNAVINST 5000.2F",
    "title": "SECNAVINST 5000.2F - ACQUISITION AND CAPABILITIES GUIDEBOOK",
    "subject": "ACQUISITION AND CAPABILITIES GUIDEBOOK",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-00%20General%20Management/5000.2F.pdf",
    "pubDate": "2022-03-08T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5000.2F - ACQUISITION AND CAPABILITIES GUIDEBOOK",
    "category": "General Management Security and Safety",
    "effectiveDate": "2022-03-08"
  },
  {
    "id": "SECNAVINST 5520.3D",
    "title": "SECNAVINST 5520.3D - CRIMINAL INVESTIGATIONS AND LAW ENFORCEMENT",
    "subject": "CRIMINAL INVESTIGATIONS AND LAW ENFORCEMENT",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-05%20Security/5520.3D.pdf",
    "pubDate": "2022-02-01T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5520.3D - CRIMINAL INVESTIGATIONS AND LAW ENFORCEMENT",
    "category": "General Management Security and Safety",
    "effectiveDate": "2022-02-01"
  },
  {
    "id": "SECNAVINST 1752.4C",
    "title": "SECNAVINST 1752.4C - SEXUAL ASSAULT PREVENTION AND RESPONSE",
    "subject": "SEXUAL ASSAULT PREVENTION AND RESPONSE",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-07%20Morale%20and%20Community%20Services/1752.4C.pdf",
    "pubDate": "2022-01-14T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1752.4C - SEXUAL ASSAULT PREVENTION AND RESPONSE",
    "category": "Military Personnel Support",
    "effectiveDate": "2022-01-14"
  },
  {
    "id": "SECNAVINST 5720.44D",
    "title": "SECNAVINST 5720.44D - PUBLIC AFFAIRS POLICY AND REGULATIONS",
    "subject": "PUBLIC AFFAIRS POLICY AND REGULATIONS",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-07%20Public%20Affairs/5720.44D.pdf",
    "pubDate": "2021-11-30T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5720.44D - PUBLIC AFFAIRS POLICY AND REGULATIONS",
    "category": "General Management Security and Safety",
    "effectiveDate": "2021-11-30"
  },
  {
    "id": "SECNAVINST 11011.36",
    "title": "SECNAVINST 11011.36 - INTEGRATED NATURAL RESOURCES MANAGEMENT PLAN",
    "subject": "INTEGRATED NATURAL RESOURCES MANAGEMENT PLAN",
    "link": "https://www.secnav.navy.mil/doni/Directives/11000%20Facilities%20and%20Activities%20Ashore/11-01%20Shore%20Facilities/11011.36.pdf",
    "pubDate": "2021-10-07T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 11011.36 - INTEGRATED NATURAL RESOURCES MANAGEMENT PLAN",
    "category": "Facilities and Activities Ashore",
    "effectiveDate": "2021-10-07"
  },
  {
    "id": "SECNAVINST 5216.5E",
    "title": "SECNAVINST 5216.5E - DEPARTMENT OF THE NAVY CORRESPONDENCE MANUAL",
    "subject": "DEPARTMENT OF THE NAVY CORRESPONDENCE MANUAL",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-02%20Information%20Management/5216.5E.pdf",
    "pubDate": "2021-09-14T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5216.5E - DEPARTMENT OF THE NAVY CORRESPONDENCE MANUAL",
    "category": "General Management Security and Safety",
    "effectiveDate": "2021-09-14"
  },
  {
    "id": "SECNAVINST 5500.32",
    "title": "SECNAVINST 5500.32 - CRITICAL INFRASTRUCTURE PROTECTION",
    "subject": "CRITICAL INFRASTRUCTURE PROTECTION",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-05%20Security/5500.32.pdf",
    "pubDate": "2021-07-22T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5500.32 - CRITICAL INFRASTRUCTURE PROTECTION",
    "category": "General Management Security and Safety",
    "effectiveDate": "2021-07-22"
  },
  {
    "id": "SECNAVINST 5100.10L",
    "title": "SECNAVINST 5100.10L - SAFETY PROGRAM",
    "subject": "SAFETY PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/06000%20Safety%20and%20Occupational%20Health/06-01%20Safety/5100.10L.pdf",
    "pubDate": "2021-06-08T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5100.10L - SAFETY PROGRAM",
    "category": "Safety and Occupational Health",
    "effectiveDate": "2021-06-08"
  },
  {
    "id": "SECNAVINST 1420.3",
    "title": "SECNAVINST 1420.3 - DEPARTMENT OF THE NAVY ENLISTED TO OFFICER COMMISSIONING PROGRAMS",
    "subject": "DEPARTMENT OF THE NAVY ENLISTED TO OFFICER COMMISSIONING PROGRAMS",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-04%20Personnel%20Strength%20and%20Distribution/1420.3.pdf",
    "pubDate": "2021-05-10T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1420.3 - DEPARTMENT OF THE NAVY ENLISTED TO OFFICER COMMISSIONING PROGRAMS",
    "category": "Military Personnel Support",
    "effectiveDate": "2021-05-10"
  },
  {
    "id": "SECNAVINST 3502.4C",
    "title": "SECNAVINST 3502.4C - EXERCISE OF MILITARY AUTHORITY",
    "subject": "EXERCISE OF MILITARY AUTHORITY",
    "link": "https://www.secnav.navy.mil/doni/Directives/03000%20Naval%20Operations%20and%20Readiness/03-05%20Training%20and%20Readiness/3502.4C.pdf",
    "pubDate": "2021-04-05T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 3502.4C - EXERCISE OF MILITARY AUTHORITY",
    "category": "Naval Operations and Readiness",
    "effectiveDate": "2021-04-05"
  },
  {
    "id": "SECNAVINST 7220.88A",
    "title": "SECNAVINST 7220.88A - CIVILIAN PREMIUM PAY",
    "subject": "CIVILIAN PREMIUM PAY",
    "link": "https://www.secnav.navy.mil/doni/Directives/07000%20Financial%20Management/07-02%20Civilian%20Pay/7220.88A.pdf",
    "pubDate": "2021-03-25T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 7220.88A - CIVILIAN PREMIUM PAY",
    "category": "Financial Management",
    "effectiveDate": "2021-03-25"
  },
  {
    "id": "SECNAVINST 1740.5",
    "title": "SECNAVINST 1740.5 - EXCEPTIONAL FAMILY MEMBER PROGRAM",
    "subject": "EXCEPTIONAL FAMILY MEMBER PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-07%20Morale%20and%20Community%20Services/1740.5.pdf",
    "pubDate": "2021-02-28T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1740.5 - EXCEPTIONAL FAMILY MEMBER PROGRAM",
    "category": "Military Personnel Support",
    "effectiveDate": "2021-02-28"
  },
  {
    "id": "SECNAVINST 4400.2",
    "title": "SECNAVINST 4400.2 - POLICY FOR NAVY FLEET READINESS LOGISTICS",
    "subject": "POLICY FOR NAVY FLEET READINESS LOGISTICS",
    "link": "https://www.secnav.navy.mil/doni/Directives/04000%20Logistical%20Support%20and%20Services/04-04%20Maintenance/4400.2.pdf",
    "pubDate": "2021-01-19T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 4400.2 - POLICY FOR NAVY FLEET READINESS LOGISTICS",
    "category": "Logistical Support and Services",
    "effectiveDate": "2021-01-19"
  },
  {
    "id": "SECNAVINST 11010.9D",
    "title": "SECNAVINST 11010.9D - SHORE INSTALLATION MANAGEMENT",
    "subject": "SHORE INSTALLATION MANAGEMENT",
    "link": "https://www.secnav.navy.mil/doni/Directives/11000%20Facilities%20and%20Activities%20Ashore/11-01%20Shore%20Facilities/11010.9D.pdf",
    "pubDate": "2020-12-16T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 11010.9D - SHORE INSTALLATION MANAGEMENT",
    "category": "Facilities and Activities Ashore",
    "effectiveDate": "2020-12-16"
  },
  {
    "id": "SECNAVINST 1754.8",
    "title": "SECNAVINST 1754.8 - FAMILY ADVOCACY PROGRAM",
    "subject": "FAMILY ADVOCACY PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-07%20Morale%20and%20Community%20Services/1754.8.pdf",
    "pubDate": "2020-11-20T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1754.8 - FAMILY ADVOCACY PROGRAM",
    "category": "Military Personnel Support",
    "effectiveDate": "2020-11-20"
  },
  {
    "id": "SECNAVINST 5210.11F",
    "title": "SECNAVINST 5210.11F - DEPARTMENT OF THE NAVY PRIVACY PROGRAM",
    "subject": "DEPARTMENT OF THE NAVY PRIVACY PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-02%20Information%20Management/5210.11F.pdf",
    "pubDate": "2020-10-05T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5210.11F - DEPARTMENT OF THE NAVY PRIVACY PROGRAM",
    "category": "General Management Security and Safety",
    "effectiveDate": "2020-10-05"
  },
  {
    "id": "SECNAVINST 5820.8A",
    "title": "SECNAVINST 5820.8A - RELEASE OF OFFICIAL INFORMATION IN LITIGATION",
    "subject": "RELEASE OF OFFICIAL INFORMATION IN LITIGATION",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-08%20Legal%20Affairs/5820.8A.pdf",
    "pubDate": "2020-09-11T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5820.8A - RELEASE OF OFFICIAL INFORMATION IN LITIGATION",
    "category": "General Management Security and Safety",
    "effectiveDate": "2020-09-11"
  },
  {
    "id": "SECNAVINST 4355.1",
    "title": "SECNAVINST 4355.1 - DEPARTMENT OF THE NAVY FOOD SERVICE PROGRAM",
    "subject": "DEPARTMENT OF THE NAVY FOOD SERVICE PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/04000%20Logistical%20Support%20and%20Services/04-03%20Subsistence/4355.1.pdf",
    "pubDate": "2020-08-25T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 4355.1 - DEPARTMENT OF THE NAVY FOOD SERVICE PROGRAM",
    "category": "Logistical Support and Services",
    "effectiveDate": "2020-08-25"
  },
  {
    "id": "SECNAVINST 7000.27E",
    "title": "SECNAVINST 7000.27E - FINANCIAL MANAGEMENT POLICY MANUAL",
    "subject": "FINANCIAL MANAGEMENT POLICY MANUAL",
    "link": "https://www.secnav.navy.mil/doni/Directives/07000%20Financial%20Management/07-00%20General%20Financial%20Management/7000.27E.pdf",
    "pubDate": "2020-07-14T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 7000.27E - FINANCIAL MANAGEMENT POLICY MANUAL",
    "category": "Financial Management",
    "effectiveDate": "2020-07-14"
  },
  {
    "id": "SECNAVINST 1640.10C",
    "title": "SECNAVINST 1640.10C - CORRECTIONS MANUAL",
    "subject": "CORRECTIONS MANUAL",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-06%20Personnel%20Security%20and%20Law/1640.10C.pdf",
    "pubDate": "2020-06-18T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1640.10C - CORRECTIONS MANUAL",
    "category": "Military Personnel Support",
    "effectiveDate": "2020-06-18"
  },
  {
    "id": "SECNAVINST 3300.1D",
    "title": "SECNAVINST 3300.1D - NAVAL INTELLIGENCE ACTIVITIES",
    "subject": "NAVAL INTELLIGENCE ACTIVITIES",
    "link": "https://www.secnav.navy.mil/doni/Directives/03000%20Naval%20Operations%20and%20Readiness/03-03%20Intelligence%20Operations/3300.1D.pdf",
    "pubDate": "2020-05-12T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 3300.1D - NAVAL INTELLIGENCE ACTIVITIES",
    "category": "Naval Operations and Readiness",
    "effectiveDate": "2020-05-12"
  },
  {
    "id": "SECNAVINST 5510.30C",
    "title": "SECNAVINST 5510.30C - DEPARTMENT OF THE NAVY PERSONNEL SECURITY PROGRAM",
    "subject": "DEPARTMENT OF THE NAVY PERSONNEL SECURITY PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-05%20Security/5510.30C.pdf",
    "pubDate": "2020-04-09T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5510.30C - DEPARTMENT OF THE NAVY PERSONNEL SECURITY PROGRAM",
    "category": "General Management Security and Safety",
    "effectiveDate": "2020-04-09"
  },
  {
    "id": "SECNAVINST 1401.3C",
    "title": "SECNAVINST 1401.3C - LEAVE AND LIBERTY POLICY AND ADMINISTRATION",
    "subject": "LEAVE AND LIBERTY POLICY AND ADMINISTRATION",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-04%20Personnel%20Strength%20and%20Distribution/1401.3C.pdf",
    "pubDate": "2020-03-15T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1401.3C - LEAVE AND LIBERTY POLICY AND ADMINISTRATION",
    "category": "Military Personnel Support",
    "effectiveDate": "2020-03-15"
  },
  {
    "id": "SECNAVINST 5370.7D",
    "title": "SECNAVINST 5370.7D - STANDARDS OF CONDUCT",
    "subject": "STANDARDS OF CONDUCT",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-03%20Civilian%20Personnel/5370.7D.pdf",
    "pubDate": "2020-02-27T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5370.7D - STANDARDS OF CONDUCT",
    "category": "General Management Security and Safety",
    "effectiveDate": "2020-02-27"
  },
  {
    "id": "SECNAVINST 12410.25C",
    "title": "SECNAVINST 12410.25C - CIVILIAN TRAINING AND DEVELOPMENT",
    "subject": "CIVILIAN TRAINING AND DEVELOPMENT",
    "link": "https://www.secnav.navy.mil/doni/Directives/12000%20Civilian%20Personnel/12-04%20Training/12410.25C.pdf",
    "pubDate": "2020-01-08T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 12410.25C - CIVILIAN TRAINING AND DEVELOPMENT",
    "category": "Civilian Personnel",
    "effectiveDate": "2020-01-08"
  },
  {
    "id": "SECNAVINST 5300.26F",
    "title": "SECNAVINST 5300.26F - DEPARTMENT OF THE NAVY CIVILIAN HUMAN RESOURCES MANUAL",
    "subject": "DEPARTMENT OF THE NAVY CIVILIAN HUMAN RESOURCES MANUAL",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-03%20Civilian%20Personnel/5300.26F.pdf",
    "pubDate": "2019-12-03T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5300.26F - DEPARTMENT OF THE NAVY CIVILIAN HUMAN RESOURCES MANUAL",
    "category": "General Management Security and Safety",
    "effectiveDate": "2019-12-03"
  },
  {
    "id": "SECNAVINST 3501.1",
    "title": "SECNAVINST 3501.1 - DEPARTMENT OF THE NAVY READINESS REPORTING SYSTEM",
    "subject": "DEPARTMENT OF THE NAVY READINESS REPORTING SYSTEM",
    "link": "https://www.secnav.navy.mil/doni/Directives/03000%20Naval%20Operations%20and%20Readiness/03-05%20Training%20and%20Readiness/3501.1.pdf",
    "pubDate": "2019-11-28T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 3501.1 - DEPARTMENT OF THE NAVY READINESS REPORTING SYSTEM",
    "category": "Naval Operations and Readiness",
    "effectiveDate": "2019-11-28"
  },
  {
    "id": "SECNAVINST 12250.4A",
    "title": "SECNAVINST 12250.4A - CIVILIAN EMPLOYEE ASSISTANCE PROGRAM",
    "subject": "CIVILIAN EMPLOYEE ASSISTANCE PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/12000%20Civilian%20Personnel/12-02%20Employee%20Programs/12250.4A.pdf",
    "pubDate": "2019-11-13T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 12250.4A - CIVILIAN EMPLOYEE ASSISTANCE PROGRAM",
    "category": "Civilian Personnel",
    "effectiveDate": "2019-11-13"
  },
  {
    "id": "SECNAVINST 5510.36B",
    "title": "SECNAVINST 5510.36B - DEPARTMENT OF THE NAVY INFORMATION SECURITY PROGRAM",
    "subject": "DEPARTMENT OF THE NAVY INFORMATION SECURITY PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-05%20Security/5510.36B.pdf",
    "pubDate": "2019-10-18T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5510.36B - DEPARTMENT OF THE NAVY INFORMATION SECURITY PROGRAM",
    "category": "General Management Security and Safety",
    "effectiveDate": "2019-10-18"
  },
  {
    "id": "SECNAVINST 1520.5B",
    "title": "SECNAVINST 1520.5B - EDUCATION OF MILITARY MEMBERS",
    "subject": "EDUCATION OF MILITARY MEMBERS",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-05%20Personnel%20Training/1520.5B.pdf",
    "pubDate": "2019-09-30T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1520.5B - EDUCATION OF MILITARY MEMBERS",
    "category": "Military Personnel Support",
    "effectiveDate": "2019-09-30"
  },
  {
    "id": "SECNAVINST 1650.1J",
    "title": "SECNAVINST 1650.1J - NAVY AND MARINE CORPS AWARDS MANUAL",
    "subject": "NAVY AND MARINE CORPS AWARDS MANUAL",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-06%20Personnel%20Security%20and%20Law/1650.1J.pdf",
    "pubDate": "2019-08-15T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1650.1J - NAVY AND MARINE CORPS AWARDS MANUAL",
    "category": "Military Personnel Support",
    "effectiveDate": "2019-08-15"
  },
  {
    "id": "SECNAVINST 7320.10A",
    "title": "SECNAVINST 7320.10A - DEPARTMENT OF THE NAVY PERSONAL PROPERTY CLAIMS",
    "subject": "DEPARTMENT OF THE NAVY PERSONAL PROPERTY CLAIMS",
    "link": "https://www.secnav.navy.mil/doni/Directives/07000%20Financial%20Management/07-03%20Claims/7320.10A.pdf",
    "pubDate": "2019-08-01T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 7320.10A - DEPARTMENT OF THE NAVY PERSONAL PROPERTY CLAIMS",
    "category": "Financial Management",
    "effectiveDate": "2019-08-01"
  },
  {
    "id": "SECNAVINST 1850.4F",
    "title": "SECNAVINST 1850.4F - DEPARTMENT OF THE NAVY DISABILITY EVALUATION MANUAL",
    "subject": "DEPARTMENT OF THE NAVY DISABILITY EVALUATION MANUAL",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-08%20Casualty%20and%20Mortuary%20Affairs/1850.4F.pdf",
    "pubDate": "2019-07-08T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1850.4F - DEPARTMENT OF THE NAVY DISABILITY EVALUATION MANUAL",
    "category": "Military Personnel Support",
    "effectiveDate": "2019-07-08"
  },
  {
    "id": "SECNAVINST 5030.8D",
    "title": "SECNAVINST 5030.8D - GENERAL RECORDS SCHEDULES",
    "subject": "GENERAL RECORDS SCHEDULES",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-00%20General%20Management/5030.8D.pdf",
    "pubDate": "2019-06-12T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5030.8D - GENERAL RECORDS SCHEDULES",
    "category": "General Management Security and Safety",
    "effectiveDate": "2019-06-12"
  },
  {
    "id": "SECNAVINST 5102.1",
    "title": "SECNAVINST 5102.1 - ACCIDENT INVESTIGATION AND REPORTING",
    "subject": "ACCIDENT INVESTIGATION AND REPORTING",
    "link": "https://www.secnav.navy.mil/doni/Directives/06000%20Safety%20and%20Occupational%20Health/06-01%20Safety/5102.1.pdf",
    "pubDate": "2019-05-22T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5102.1 - ACCIDENT INVESTIGATION AND REPORTING",
    "category": "Safety and Occupational Health",
    "effectiveDate": "2019-05-22"
  },
  {
    "id": "SECNAVINST 4440.35",
    "title": "SECNAVINST 4440.35 - NAVY HAZARDOUS MATERIAL CONTROL AND MANAGEMENT",
    "subject": "NAVY HAZARDOUS MATERIAL CONTROL AND MANAGEMENT",
    "link": "https://www.secnav.navy.mil/doni/Directives/04000%20Logistical%20Support%20and%20Services/04-04%20Maintenance/4440.35.pdf",
    "pubDate": "2019-04-30T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 4440.35 - NAVY HAZARDOUS MATERIAL CONTROL AND MANAGEMENT",
    "category": "Logistical Support and Services",
    "effectiveDate": "2019-04-30"
  },
  {
    "id": "SECNAVINST 1000.9B F",
    "title": "SECNAVINST 1000.9B F - CODE OF CONDUCT FOR MEMBERS OF THE ARMED FORCES OF THE UNITED STATES",
    "subject": "CODE OF CONDUCT FOR MEMBERS OF THE ARMED FORCES OF THE UNITED STATES",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-01%20General%20Military%20Personnel%20Records/1000.9B%20F.pdf",
    "pubDate": "2019-04-12T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1000.9B F - CODE OF CONDUCT FOR MEMBERS OF THE ARMED FORCES OF THE UNITED STATES",
    "category": "Military Personnel Support",
    "effectiveDate": "2019-04-12"
  },
  {
    "id": "SECNAVINST 5800.13E",
    "title": "SECNAVINST 5800.13E - DEPARTMENT OF THE NAVY LAW OF ARMED CONFLICT PROGRAM",
    "subject": "DEPARTMENT OF THE NAVY LAW OF ARMED CONFLICT PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-08%20Legal%20Affairs/5800.13E.pdf",
    "pubDate": "2019-03-06T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5800.13E - DEPARTMENT OF THE NAVY LAW OF ARMED CONFLICT PROGRAM",
    "category": "General Management Security and Safety",
    "effectiveDate": "2019-03-06"
  },
  {
    "id": "SECNAVINST 4000.35D",
    "title": "SECNAVINST 4000.35D - DEPARTMENT OF THE NAVY ACQUISITION INTEGRITY PROGRAM",
    "subject": "DEPARTMENT OF THE NAVY ACQUISITION INTEGRITY PROGRAM",
    "link": "https://www.secnav.navy.mil/doni/Directives/04000%20Logistical%20Support%20and%20Services/04-00%20General%20Logistics/4000.35D.pdf",
    "pubDate": "2019-02-14T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 4000.35D - DEPARTMENT OF THE NAVY ACQUISITION INTEGRITY PROGRAM",
    "category": "Logistical Support and Services",
    "effectiveDate": "2019-02-14"
  },
  {
    "id": "SECNAVINST 1000.7G",
    "title": "SECNAVINST 1000.7G - INTERSERVICE TRANSFER OF OFFICERS",
    "subject": "INTERSERVICE TRANSFER OF OFFICERS",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-01%20General%20Military%20Personnel%20Records/1000.7G.pdf",
    "pubDate": "2019-01-23T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1000.7G - INTERSERVICE TRANSFER OF OFFICERS",
    "category": "Military Personnel Support",
    "effectiveDate": "2019-01-23"
  },
  {
    "id": "SECNAVINST 1000.10B",
    "title": "SECNAVINST 1000.10B - DEPARTMENT OF THE NAVY POLICY ON PARENTHOOD AND PREGNANCY",
    "subject": "DEPARTMENT OF THE NAVY POLICY ON PARENTHOOD AND PREGNANCY",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-01%20General%20Military%20Personnel%20Records/1000.10B.pdf",
    "pubDate": "2019-01-16T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1000.10B - DEPARTMENT OF THE NAVY POLICY ON PARENTHOOD AND PREGNANCY",
    "category": "Military Personnel Support",
    "effectiveDate": "2019-01-16"
  },
  {
    "id": "SECNAVINST 1730.9",
    "title": "SECNAVINST 1730.9 - CONFIDENTIAL COMMUNICATIONS TO CHAPLAINS",
    "subject": "CONFIDENTIAL COMMUNICATIONS TO CHAPLAINS",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-07%20Morale%20and%20Community%20Services/1730.9.pdf",
    "pubDate": "2018-12-05T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1730.9 - CONFIDENTIAL COMMUNICATIONS TO CHAPLAINS",
    "category": "Military Personnel Support",
    "effectiveDate": "2018-12-05"
  },
  {
    "id": "SECNAVINST 5430.7R",
    "title": "SECNAVINST 5430.7R - ASSIGNMENT OF RESPONSIBILITIES AND AUTHORITIES IN THE OFFICE OF THE SECRETARY OF THE NAVY",
    "subject": "ASSIGNMENT OF RESPONSIBILITIES AND AUTHORITIES IN THE OFFICE OF THE SECRETARY OF THE NAVY",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-04%20Organization/5430.7R.pdf",
    "pubDate": "2018-11-16T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5430.7R - ASSIGNMENT OF RESPONSIBILITIES AND AUTHORITIES IN THE OFFICE OF THE SECRETARY OF THE NAVY",
    "category": "General Management Security and Safety",
    "effectiveDate": "2018-11-16"
  },
  {
    "id": "SECNAVINST 7000.14",
    "title": "SECNAVINST 7000.14 - DEPARTMENT OF DEFENSE FINANCIAL MANAGEMENT REGULATION",
    "subject": "DEPARTMENT OF DEFENSE FINANCIAL MANAGEMENT REGULATION",
    "link": "https://www.secnav.navy.mil/doni/Directives/07000%20Financial%20Management/07-00%20General%20Financial%20Management/7000.14.pdf",
    "pubDate": "2018-10-30T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 7000.14 - DEPARTMENT OF DEFENSE FINANCIAL MANAGEMENT REGULATION",
    "category": "Financial Management",
    "effectiveDate": "2018-10-30"
  },
  {
    "id": "SECNAVINST 4280.1B",
    "title": "SECNAVINST 4280.1B - GOVERNMENT PROPERTY IN THE POSSESSION OF CONTRACTORS",
    "subject": "GOVERNMENT PROPERTY IN THE POSSESSION OF CONTRACTORS",
    "link": "https://www.secnav.navy.mil/doni/Directives/04000%20Logistical%20Support%20and%20Services/04-02%20Supply%20Operations/4280.1B.pdf",
    "pubDate": "2018-09-07T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 4280.1B - GOVERNMENT PROPERTY IN THE POSSESSION OF CONTRACTORS",
    "category": "Logistical Support and Services",
    "effectiveDate": "2018-09-07"
  },
  {
    "id": "SECNAVINST 1412.9",
    "title": "SECNAVINST 1412.9 - OVERSEAS AREA SCREENING CRITERIA",
    "subject": "OVERSEAS AREA SCREENING CRITERIA",
    "link": "https://www.secnav.navy.mil/doni/Directives/01000%20Military%20Personnel%20Support/01-04%20Personnel%20Strength%20and%20Distribution/1412.9.pdf",
    "pubDate": "2018-08-22T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 1412.9 - OVERSEAS AREA SCREENING CRITERIA",
    "category": "Military Personnel Support",
    "effectiveDate": "2018-08-22"
  },
  {
    "id": "SECNAVINST 5211.5F",
    "title": "SECNAVINST 5211.5F - DEPARTMENT OF THE NAVY POLICY FOR DISCLOSURE OF CLASSIFIED MILITARY INFORMATION",
    "subject": "DEPARTMENT OF THE NAVY POLICY FOR DISCLOSURE OF CLASSIFIED MILITARY INFORMATION",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-02%20Information%20Management/5211.5F.pdf",
    "pubDate": "2018-07-20T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5211.5F - DEPARTMENT OF THE NAVY POLICY FOR DISCLOSURE OF CLASSIFIED MILITARY INFORMATION",
    "category": "General Management Security and Safety",
    "effectiveDate": "2018-07-20"
  },
  {
    "id": "SECNAVINST 5580.1A",
    "title": "SECNAVINST 5580.1A - LAW ENFORCEMENT AND PHYSICAL SECURITY",
    "subject": "LAW ENFORCEMENT AND PHYSICAL SECURITY",
    "link": "https://www.secnav.navy.mil/doni/Directives/05000%20General%20Management%20Security%20and%20Safety/05-05%20Security/5580.1A.pdf",
    "pubDate": "2018-05-25T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 5580.1A - LAW ENFORCEMENT AND PHYSICAL SECURITY",
    "category": "General Management Security and Safety",
    "effectiveDate": "2018-05-25"
  },
  {
    "id": "SECNAVINST 11011.47A",
    "title": "SECNAVINST 11011.47A - ENVIRONMENTAL PLANNING FOR DON ACTIONS",
    "subject": "ENVIRONMENTAL PLANNING FOR DON ACTIONS",
    "link": "https://www.secnav.navy.mil/doni/Directives/11000%20Facilities%20and%20Activities%20Ashore/11-01%20Shore%20Facilities/11011.47A.pdf",
    "pubDate": "2018-04-11T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 11011.47A - ENVIRONMENTAL PLANNING FOR DON ACTIONS",
    "category": "Facilities and Activities Ashore",
    "effectiveDate": "2018-04-11"
  },
  {
    "id": "SECNAVINST 3070.2B",
    "title": "SECNAVINST 3070.2B - RULES OF ENGAGEMENT",
    "subject": "RULES OF ENGAGEMENT",
    "link": "https://www.secnav.navy.mil/doni/Directives/03000%20Naval%20Operations%20and%20Readiness/03-00%20General%20Naval%20Operations/3070.2B.pdf",
    "pubDate": "2018-03-22T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 3070.2B - RULES OF ENGAGEMENT",
    "category": "Naval Operations and Readiness",
    "effectiveDate": "2018-03-22"
  },
  {
    "id": "SECNAVINST 3006.1",
    "title": "SECNAVINST 3006.1 - DEPARTMENT OF THE NAVY PARTICIPATION IN NATIONAL SECURITY AGENCY",
    "subject": "DEPARTMENT OF THE NAVY PARTICIPATION IN NATIONAL SECURITY AGENCY",
    "link": "https://www.secnav.navy.mil/doni/Directives/03000%20Naval%20Operations%20and%20Readiness/03-00%20General%20Naval%20Operations/3006.1.pdf",
    "pubDate": "2017-06-15T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 3006.1 - DEPARTMENT OF THE NAVY PARTICIPATION IN NATIONAL SECURITY AGENCY",
    "category": "Naval Operations and Readiness",
    "effectiveDate": "2017-06-15"
  },
  {
    "id": "SECNAVINST 12335.1A",
    "title": "SECNAVINST 12335.1A - NAVY TOTAL FORCE MANPOWER POLICIES AND PROCEDURES",
    "subject": "NAVY TOTAL FORCE MANPOWER POLICIES AND PROCEDURES",
    "link": "https://www.secnav.navy.mil/doni/Directives/12000%20Civilian%20Personnel/12-03%20Workforce%20Management/12335.1A.pdf",
    "pubDate": "2015-06-24T00:00:00.000Z",
    "description": "Secretary of the Navy Instruction 12335.1A - NAVY TOTAL FORCE MANPOWER POLICIES AND PROCEDURES",
    "category": "Civilian Personnel",
    "effectiveDate": "2015-06-24"
  }
];

// Metadata
const SECNAV_META = {
  sourceUrl: 'https://www.secnav.navy.mil/doni/Directives/Forms/doniAllInstructions.aspx',
  generatedAt: '2025-12-22T07:48:39.870Z',
  totalRecords: 53,
  categories: ["Military Personnel Support","Naval Operations and Readiness","Logistical Support and Services","General Management Security and Safety","Safety and Occupational Health","Financial Management","Facilities and Activities Ashore","Civilian Personnel"],
  lastUpdate: '2025-12-22T07:48:39.870Z',
  note: 'Real SECNAV instructions from DONI - links verified against official source'
};

// Export for use in application
if (typeof window !== 'undefined') {
  window.SECNAV_DIRECTIVES = SECNAV_DIRECTIVES;
  window.SECNAV_META = SECNAV_META;
}

// Also support module exports for testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    SECNAV_DIRECTIVES,
    SECNAV_META
  };
}
