/**
 * SECNAV Directives Data
 *
 * Auto-generated from Navy DONI SharePoint Site
 * Source: https://www.secnav.navy.mil/doni/SECNAV%20Manuals1/Forms/AllItems.aspx?View=%7B71bc9fed-cda6-4e2a-b781-43a972cc6a98%7D&SortField=Effective_x0020_Date&SortDir=Desc
 * Generated: 2025-12-17T06:27:59.520Z
 * Total Records: 0
 *
 * This file is automatically generated by scripts/fetch-secnav.mjs
 * DO NOT EDIT MANUALLY
 */

// SECNAV directives data structure
const SECNAV_DIRECTIVES = [];

// Metadata
const SECNAV_META = {
  sourceUrl: 'https://www.secnav.navy.mil/doni/SECNAV%20Manuals1/Forms/AllItems.aspx?View=%7B71bc9fed-cda6-4e2a-b781-43a972cc6a98%7D&SortField=Effective_x0020_Date&SortDir=Desc',
  generatedAt: '2025-12-17T06:27:59.520Z',
  totalRecords: 0,
  lastUpdate: '2025-12-17T06:27:59.520Z'
};

// Export for use in application
if (typeof window !== 'undefined') {
  window.SECNAV_DIRECTIVES = SECNAV_DIRECTIVES;
  window.SECNAV_META = SECNAV_META;
}

// Also support module exports for testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    SECNAV_DIRECTIVES,
    SECNAV_META
  };
}
