/**
 * YouTube Videos Data
 *
 * Auto-generated from Semper Admin YouTube channel
 * Source: https://www.youtube.com/@SemperAdmin
 * Channel ID: UCob5u7jsXrdca9vmarYJ0Cg
 * Generated: 2025-11-17T03:06:46.844Z
 * Total Videos: 0
 *
 * This file is automatically generated by scripts/fetch-youtube.mjs
 * DO NOT EDIT MANUALLY
 */

// YouTube video data structure
const YOUTUBE_VIDEOS = [];

// Export for use in frontend (if using modules) or make globally available
if (typeof module !== 'undefined' && module.exports) {
  module.exports = YOUTUBE_VIDEOS;
}

// Make available globally for browser usage
if (typeof window !== 'undefined') {
  window.YOUTUBE_VIDEOS = YOUTUBE_VIDEOS;
}
