/**
 * YouTube Videos Data
 *
 * This file will be auto-generated daily by GitHub Actions
 * Source: Semper Admin YouTube channel
 * Channel ID: UCob5u7jsXrdca9vmarYJ0Cg
 * Schedule: Daily at 01:00 HST (11:00 UTC)
 *
 * Generated by: scripts/fetch-youtube.mjs
 * Workflow: .github/workflows/update-youtube-data.yml
 *
 * PLACEHOLDER: No data yet - waiting for first automated fetch
 */

// Empty array - will be populated by GitHub Actions workflow
const YOUTUBE_VIDEOS = [];

// Export for use in frontend (if using modules) or make globally available
if (typeof module !== 'undefined' && module.exports) {
  module.exports = YOUTUBE_VIDEOS;
}

// Make available globally for browser usage
if (typeof window !== 'undefined') {
  window.YOUTUBE_VIDEOS = YOUTUBE_VIDEOS;
}
