/**
 * YouTube Videos Data
 *
 * Auto-generated from Semper Admin YouTube channel
 * Source: https://www.youtube.com/@SemperAdmin
 * Channel ID: UCob5u7jsXrdca9vmarYJ0Cg
 * Generated: 2025-12-31T11:16:15.931Z
 * Total Videos: 75
 *
 * This file is automatically generated by scripts/fetch-youtube.mjs
 * DO NOT EDIT MANUALLY
 */

// YouTube video data structure
const YOUTUBE_VIDEOS = [
  {
    "id": "eZmvAOsgOqE",
    "title": "Large Language Models: Drafting Professional Emails in Seconds",
    "description": "In this tutorial, learn how to use DoD-approved AI tools transforming bullet points into polished professional correspondence in ...",
    "publishedAt": "2025-12-31T10:01:10Z",
    "thumbnail": "https://i.ytimg.com/vi/eZmvAOsgOqE/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "2cVS6oXdWZs",
    "title": "Promotions: Promotion Folder Part 6 - Miscellaneous",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 6 requirements documenting miscellaneous cases handling ...",
    "publishedAt": "2025-12-29T10:00:04Z",
    "thumbnail": "https://i.ytimg.com/vi/2cVS6oXdWZs/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Lj3jhwyqKVE",
    "title": "Promotions: Promotion Folder Part 5 - Not Recommended After Select Grade",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 5 requirements documenting not recommended after select grade ...",
    "publishedAt": "2025-12-26T10:00:38Z",
    "thumbnail": "https://i.ytimg.com/vi/Lj3jhwyqKVE/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "sgnCngRQ6Us",
    "title": "Promotions: Promotion Folder Part 4 - Select Grade Documentation",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 4 requirements documenting promotion execution proving proper ...",
    "publishedAt": "2025-12-24T10:01:37Z",
    "thumbnail": "https://i.ytimg.com/vi/sgnCngRQ6Us/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "vUiKA-jW1SA",
    "title": "Promotions: Promotion Folder Part 3 - Promotion Authority",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 3 requirements documenting promotion authority proving legal ...",
    "publishedAt": "2025-12-22T10:01:38Z",
    "thumbnail": "https://i.ytimg.com/vi/vUiKA-jW1SA/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "lvwtZ-v1sNU",
    "title": "Promotions: Promotion Folder Part 2 - Recommendation Rosters",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 2 requirements documenting recommendation processing through ...",
    "publishedAt": "2025-12-19T10:01:24Z",
    "thumbnail": "https://i.ytimg.com/vi/lvwtZ-v1sNU/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "u1RQjABRh1s",
    "title": "Promotions: Promotion Folder Part 1 - Missing Training and JEPES Occasions",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 1 requirements documenting training accountability and JEPES ...",
    "publishedAt": "2025-12-17T10:01:33Z",
    "thumbnail": "https://i.ytimg.com/vi/u1RQjABRh1s/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "xkF5bUy349s",
    "title": "Promotions: Understanding the Promotion Folder",
    "description": "In this tutorial, learn the comprehensive promotion folder organizational structure and purpose maintaining proper promotion ...",
    "publishedAt": "2025-12-15T10:01:32Z",
    "thumbnail": "https://i.ytimg.com/vi/xkF5bUy349s/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "l1emYAOT8HY",
    "title": "Separations and Retirement: Post-Retirement (0-12 Months)",
    "description": "In this tutorial, learn the comprehensive post-retirement phase spanning 0-12 months after separation that establishes civilian life ...",
    "publishedAt": "2025-12-12T10:01:28Z",
    "thumbnail": "https://i.ytimg.com/vi/l1emYAOT8HY/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Eh6X7LWx0Ow",
    "title": "Separations and Retirement: Final Phase (Month of Retirement)",
    "description": "In this tutorial, learn the comprehensive final phase during month of retirement that completes active duty service through ...",
    "publishedAt": "2025-12-10T10:00:32Z",
    "thumbnail": "https://i.ytimg.com/vi/Eh6X7LWx0Ow/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Jk0mU_vhf4I",
    "title": "Separations and Retirement: Final Preparations &amp; Outprocessing (2-0 Months)",
    "description": "In this tutorial, learn the comprehensive final preparations and outprocessing phase spanning months 2-0 before separation that ...",
    "publishedAt": "2025-12-08T10:00:27Z",
    "thumbnail": "https://i.ytimg.com/vi/Jk0mU_vhf4I/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "UXrZ3IHkM-I",
    "title": "Separations and Retirement: Documentation, Legal &amp; Ceremony Planning (4-2 Months)",
    "description": "In this tutorial, learn the comprehensive documentation, legal, and ceremony planning phase spanning months 4-2 before ...",
    "publishedAt": "2025-12-05T10:01:01Z",
    "thumbnail": "https://i.ytimg.com/vi/UXrZ3IHkM-I/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "2H6boXQ4Tkg",
    "title": "Separations and Retirement: Job Search &amp; Medical Readiness (6-4 Months)",
    "description": "In this tutorial, learn the comprehensive job search and medical readiness phase spanning months 6-4 before separation that ...",
    "publishedAt": "2025-12-03T10:00:06Z",
    "thumbnail": "https://i.ytimg.com/vi/2H6boXQ4Tkg/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Epb4oNH6Phk",
    "title": "Separations and Retirement: Financial, Family &amp; Terminal Leave Planning (Months 8-6)",
    "description": "In this tutorial, learn the comprehensive financial, family, and terminal leave planning phase spanning months 8-6 before ...",
    "publishedAt": "2025-12-01T10:00:20Z",
    "thumbnail": "https://i.ytimg.com/vi/Epb4oNH6Phk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Hf0yhwlaoeQ",
    "title": "Separations and Retirement: Skill Development &amp; Professional Growth (Months 10-8)",
    "description": "In this tutorial, learn the comprehensive skill development and professional growth phase spanning months 10-8 before ...",
    "publishedAt": "2025-11-28T10:00:25Z",
    "thumbnail": "https://i.ytimg.com/vi/Hf0yhwlaoeQ/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "E1Ao0Hz7QJk",
    "title": "Separations and Retirement: Foundation Building, Retirement Request, Career Foundation (12-10 Month)",
    "description": "In this tutorial, learn the comprehensive foundation building phase spanning 12-10 months before separation that initiates formal ...",
    "publishedAt": "2025-11-26T10:00:22Z",
    "thumbnail": "https://i.ytimg.com/vi/E1Ao0Hz7QJk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "eSLW1yPFfsk",
    "title": "Separations and Retirement: Medical, Family &amp; Administrative Preparation (18-12 Months)",
    "description": "In this tutorial, learn the comprehensive medical, family, and administrative preparation phase spanning 18-12 months before ...",
    "publishedAt": "2025-11-24T10:01:05Z",
    "thumbnail": "https://i.ytimg.com/vi/eSLW1yPFfsk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "fp9x376SfT0",
    "title": "Separations and Retirement: Career, Education &amp; Financial Planning (18-12 Months)",
    "description": "In this tutorial, learn the comprehensive career, education, and financial planning phase spanning 18-12 months before ...",
    "publishedAt": "2025-11-21T10:01:19Z",
    "thumbnail": "https://i.ytimg.com/vi/fp9x376SfT0/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "1FPiMOSriiM",
    "title": "Separations and Retirement: Family, Relocation &amp; Administrative Prep (24-18 Months)",
    "description": "In this tutorial, learn the comprehensive family, relocation, and administrative preparation phase spanning 24-18 months before ...",
    "publishedAt": "2025-11-19T10:00:03Z",
    "thumbnail": "https://i.ytimg.com/vi/1FPiMOSriiM/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "tK5a9qIpP2E",
    "title": "Separations and Retirement: Medical Awareness &amp; Documentation (24-18 Months)",
    "description": "In this tutorial, learn the comprehensive medical awareness and documentation phase spanning 24-18 months before separation ...",
    "publishedAt": "2025-11-17T10:01:26Z",
    "thumbnail": "https://i.ytimg.com/vi/tK5a9qIpP2E/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "1a92z2GgFlo",
    "title": "Separations and Retirement: Career Preparation &amp; Financial Foundation (24-18 Months)",
    "description": "In this tutorial, learn the comprehensive career preparation and financial foundation phase spanning 24-18 months before ...",
    "publishedAt": "2025-11-14T10:00:04Z",
    "thumbnail": "https://i.ytimg.com/vi/1a92z2GgFlo/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "QMkjX54vmnE",
    "title": "Separations and Retirement: Earliest Phase (36-24 Months)",
    "description": "In this tutorial, learn the comprehensive earliest retirement phase spanning 36-24 months before separation that establishes ...",
    "publishedAt": "2025-11-12T10:00:41Z",
    "thumbnail": "https://i.ytimg.com/vi/QMkjX54vmnE/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "5xBvwH3-gUE",
    "title": "Separations and Retirement: MMSR Resources Guide",
    "description": "In this tutorial, learn comprehensive MMSR resources that support Marines through retirement planning, separation processing, ...",
    "publishedAt": "2025-11-10T10:00:09Z",
    "thumbnail": "https://i.ytimg.com/vi/5xBvwH3-gUE/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "ej1YVBmkYC0",
    "title": "Promotions: IMOS Failures and Reductions",
    "description": "In this tutorial, learn the serious consequences of IMOS failures and reductions as specified in MARADMIN 469/24 paragraph 2.d, ...",
    "publishedAt": "2025-11-08T10:01:05Z",
    "thumbnail": "https://i.ytimg.com/vi/ej1YVBmkYC0/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "bEI64tNyBjc",
    "title": "Promotions: IMOS DOR Examples",
    "description": "In this tutorial, learn accurate IMOS date of rank calculation through practical examples demonstrating the fundamental rule that ...",
    "publishedAt": "2025-11-06T10:01:04Z",
    "thumbnail": "https://i.ytimg.com/vi/bEI64tNyBjc/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "KgrrgyHBDHk",
    "title": "Promotions: Processing IMOS Promotions",
    "description": "In this tutorial, learn the step-by-step administrative procedures for processing IMOS promotions correctly through official channels ...",
    "publishedAt": "2025-11-04T10:00:37Z",
    "thumbnail": "https://i.ytimg.com/vi/KgrrgyHBDHk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "u5ib5hoJHoI",
    "title": "Promotions: Correct Promotion Authority References",
    "description": "In this tutorial, learn the correct promotion authority references for regular, meritorious, and special promotions that ensure warrant ...",
    "publishedAt": "2025-11-03T10:01:34Z",
    "thumbnail": "https://i.ytimg.com/vi/u5ib5hoJHoI/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "ZEoLcbo3qgY",
    "title": "Promotions: IMOS for Sergeant Promotion",
    "description": "In this tutorial, learn the specific IMOS for Sergeant promotion policy detailed in MARADMIN 469/24 paragraph 2.a, identifying the ...",
    "publishedAt": "2025-11-01T10:01:03Z",
    "thumbnail": "https://i.ytimg.com/vi/ZEoLcbo3qgY/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "f2gva77QI2I",
    "title": "Promotions: IMOS for Corporal Promotion",
    "description": "In this tutorial, learn the critical policy regarding IMOS for Corporal promotion as specified in MARADMIN 469/24 paragraph 2, ...",
    "publishedAt": "2025-10-30T10:01:13Z",
    "thumbnail": "https://i.ytimg.com/vi/f2gva77QI2I/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "2EmatCjTpDk",
    "title": "Promotions: Understanding Intended MOS Promotions",
    "description": "In this tutorial, learn the administrative framework for Intended MOS (IMOS) promotions governed by MCO P1400.32D paragraph ...",
    "publishedAt": "2025-10-28T10:00:04Z",
    "thumbnail": "https://i.ytimg.com/vi/2EmatCjTpDk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "V0398Lf9boI",
    "title": "Promotions: The Snowball Effect of Missing Not Recs",
    "description": "In this tutorial, learn the devastating snowball effect of missing not rec entries that creates repetitive administrative nightmares ...",
    "publishedAt": "2025-10-27T10:00:54Z",
    "thumbnail": "https://i.ytimg.com/vi/V0398Lf9boI/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "BhT9wJIdKp0",
    "title": "Promotions: Processing SULI Promotions",
    "description": "In this tutorial, learn the administrative procedures for processing SULI promotions through the automatic selection system ...",
    "publishedAt": "2025-10-25T10:00:16Z",
    "thumbnail": "https://i.ytimg.com/vi/BhT9wJIdKp0/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "HlnErhMT8ss",
    "title": "Promotions: Why Marines Get Erroneously Promoted",
    "description": "In this tutorial, learn the root causes of erroneous Marine promotions that require administrative correction and commanding ...",
    "publishedAt": "2025-10-24T10:00:30Z",
    "thumbnail": "https://i.ytimg.com/vi/HlnErhMT8ss/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "GlLWajT-_wg",
    "title": "Promotions: SULI Effective Dates and Timing",
    "description": "In this tutorial, learn the critical SULI effective dates and timing requirements that determine when early Sergeant promotion ...",
    "publishedAt": "2025-10-23T10:00:37Z",
    "thumbnail": "https://i.ytimg.com/vi/GlLWajT-_wg/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "6DnsaQBAUrI",
    "title": "Promotions: Understanding Not Rec vs Promotion Restriction",
    "description": "In this tutorial, learn the critical differences between not recommended status and promotion restrictions that determine proper ...",
    "publishedAt": "2025-10-22T10:00:17Z",
    "thumbnail": "https://i.ytimg.com/vi/6DnsaQBAUrI/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "npsjAhPytQk",
    "title": "Promotions: Understanding TIG and TIS Requirements and Eligibility Dates",
    "description": "In this tutorial, learn the critical time-in-grade and time-in-service eligibility date calculations per MARADMIN 185/25 that ...",
    "publishedAt": "2025-10-21T10:01:31Z",
    "thumbnail": "https://i.ytimg.com/vi/npsjAhPytQk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "dqZXepAWlsY",
    "title": "Promotions: Signature Requirements for Non Rec Page 11s",
    "description": "In this tutorial, learn the correct signature requirements for Page 11 entries that distinguish between counseling acknowledgments ...",
    "publishedAt": "2025-10-20T10:01:08Z",
    "thumbnail": "https://i.ytimg.com/vi/dqZXepAWlsY/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "lu3fMl75olU",
    "title": "Promotions: Requirements for Sergeant",
    "description": "In this tutorial, learn the comprehensive Sergeant promotion requirements that build upon Corporal criteria while introducing ...",
    "publishedAt": "2025-10-18T10:01:26Z",
    "thumbnail": "https://i.ytimg.com/vi/lu3fMl75olU/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "hIk9sw17sak",
    "title": "Promotions: Requirements for Corporal",
    "description": "In this tutorial, learn the comprehensive Corporal promotion requirements that represent a significant increase in complexity ...",
    "publishedAt": "2025-10-16T10:01:14Z",
    "thumbnail": "https://i.ytimg.com/vi/hIk9sw17sak/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "ErVCGX8Boyc",
    "title": "Promotions: Delete as Erroneous Process for Promotion",
    "description": "In this tutorial, learn the critical delete as erroneous process for unauthorized promotions under MARADMIN 559/23's automated ...",
    "publishedAt": "2025-10-15T10:00:32Z",
    "thumbnail": "https://i.ytimg.com/vi/ErVCGX8Boyc/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "FerH6JR6ES4",
    "title": "Promotions: Requirements for PFC and LCpl",
    "description": "In this tutorial, learn the specific promotion requirements for Private First Class and Lance Corporal ranks, understanding the ...",
    "publishedAt": "2025-10-14T10:00:34Z",
    "thumbnail": "https://i.ytimg.com/vi/FerH6JR6ES4/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "_QlG63tb860",
    "title": "Promotions: Understanding Permanent Not Recs",
    "description": "In this tutorial, learn the comprehensive permanent not rec system established by MARADMIN 153/21 that fundamentally changed ...",
    "publishedAt": "2025-10-13T10:00:58Z",
    "thumbnail": "https://i.ytimg.com/vi/_QlG63tb860/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "SpEN9JMK5gU",
    "title": "Promotions: Understanding Training Cutoff Dates",
    "description": "In this tutorial, learn the critical training cutoff dates that determine promotion eligibility and understand the timeline that governs ...",
    "publishedAt": "2025-10-10T10:00:57Z",
    "thumbnail": "https://i.ytimg.com/vi/SpEN9JMK5gU/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Tvp4-VuKCLk",
    "title": "Promotions: Understanding the PES Score Components",
    "description": "In this tutorial, learn the comprehensive Performance Evaluation Score (PES) components that determine junior enlisted ...",
    "publishedAt": "2025-10-09T10:00:56Z",
    "thumbnail": "https://i.ytimg.com/vi/Tvp4-VuKCLk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "3TnQPlugoWs",
    "title": "Promotions: Understanding JEPES - What It Is",
    "description": "In this tutorial, learn the fundamental concepts of the Junior Enlisted Performance Evaluation System (JEPES) and its ...",
    "publishedAt": "2025-10-08T10:00:10Z",
    "thumbnail": "https://i.ytimg.com/vi/3TnQPlugoWs/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "fISj9qcLQyA",
    "title": "Education: Special Situations - Purple Heart, Colmery Act, and More",
    "description": "In this tutorial, learn the critical special situations affecting Transfer of Education Benefits including Purple Heart exceptions, ...",
    "publishedAt": "2025-10-07T10:01:00Z",
    "thumbnail": "https://i.ytimg.com/vi/fISj9qcLQyA/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "K1pFn0r_BBA",
    "title": "Education: Common Mistakes That Cost Marines Their TEB Benefits",
    "description": "In this tutorial, learn the critical mistakes that cost Marines their Transfer of Education Benefits and how to avoid these devastating ...",
    "publishedAt": "2025-10-06T10:00:34Z",
    "thumbnail": "https://i.ytimg.com/vi/K1pFn0r_BBA/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "GtSio3FH5HU",
    "title": "Education: After Approval - Managing and Modifying Benefits",
    "description": "In this tutorial, learn the essential post-approval Transfer of Education Benefits management procedures for effectively ...",
    "publishedAt": "2025-10-03T10:00:25Z",
    "thumbnail": "https://i.ytimg.com/vi/GtSio3FH5HU/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "7DOhQfMSBfI",
    "title": "Education: Who Can Receive Your Benefits? Dependent Eligibility",
    "description": "In this tutorial, learn the comprehensive dependent eligibility requirements for Transfer of Education Benefits, covering who can ...",
    "publishedAt": "2025-10-02T10:00:09Z",
    "thumbnail": "https://i.ytimg.com/vi/7DOhQfMSBfI/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "a_o_ILbMp30",
    "title": "Education: Your Service Obligation - The 48-Month Commitment",
    "description": "In this tutorial, learn the critical 48-month service obligation requirements that accompany Transfer of Education Benefits approval, ...",
    "publishedAt": "2025-10-01T10:00:02Z",
    "thumbnail": "https://i.ytimg.com/vi/a_o_ILbMp30/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "yGYtwOQVmZI",
    "title": "Education: Am I Eligible? Understanding TEB Requirements",
    "description": "In this tutorial, learn the comprehensive Transfer of Education Benefits eligibility requirements that determine whether you can ...",
    "publishedAt": "2025-09-30T10:01:46Z",
    "thumbnail": "https://i.ytimg.com/vi/yGYtwOQVmZI/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "ySe403cNWQw",
    "title": "Education: TEB Overview - What You Need to Know NOW",
    "description": "In this tutorial, learn the critical Transfer of Education Benefits (TEB) fundamentals that every Marine must understand immediately ...",
    "publishedAt": "2025-09-29T10:01:44Z",
    "thumbnail": "https://i.ytimg.com/vi/ySe403cNWQw/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Mcwc_7CeD4w",
    "title": "Pay and Entitlements: Advance Pay Incident to a PCS - Understanding the Basics",
    "description": "In this tutorial, learn the fundamental concepts of Advance Pay Incident to a PCS, a critical financial tool designed to help Marines ...",
    "publishedAt": "2025-09-04T10:00:43Z",
    "thumbnail": "https://i.ytimg.com/vi/Mcwc_7CeD4w/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "muMvxZeUfi4",
    "title": "Pay and Entitlements: BAH Waivers - Criteria and Authorization Process",
    "description": "In this tutorial, learn the comprehensive BAH waiver criteria and authorization process that can significantly impact your financial ...",
    "publishedAt": "2025-09-02T10:01:18Z",
    "thumbnail": "https://i.ytimg.com/vi/muMvxZeUfi4/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "coiOrVO8Ld4",
    "title": "Pay and Entitlements: BAH Rate Protection - Maintaining Higher Rates",
    "description": "In this tutorial, learn the essential principles of BAH Rate Protection and how it maintains your housing allowance at higher rates ...",
    "publishedAt": "2025-08-30T10:00:54Z",
    "thumbnail": "https://i.ytimg.com/vi/coiOrVO8Ld4/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Y6u61hPhDlg",
    "title": "Pay and Entitlements: Advance BAH - Repayment and Liquidation Procedures",
    "description": "In this tutorial, learn the complete Advance BAH repayment and liquidation procedures to effectively manage your financial ...",
    "publishedAt": "2025-08-28T10:01:00Z",
    "thumbnail": "https://i.ytimg.com/vi/Y6u61hPhDlg/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "qsyDoQdPmhU",
    "title": "Pay and Entitlements: Advance BAH - Application Process and Documentation Requirements",
    "description": "In this tutorial, learn the complete Advance BAH application process and documentation requirements to successfully submit your ...",
    "publishedAt": "2025-08-26T10:01:28Z",
    "thumbnail": "https://i.ytimg.com/vi/qsyDoQdPmhU/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "2iYMJIGddX8",
    "title": "Pay and Entitlements: Advance BAH - Eligibility and Authorized Uses",
    "description": "In this tutorial, learn the complete eligibility requirements and authorized uses for Advance Basic Allowance for Housing (BAH), ...",
    "publishedAt": "2025-08-23T10:00:05Z",
    "thumbnail": "https://i.ytimg.com/vi/2iYMJIGddX8/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Wg9z5jhVm5k",
    "title": "Excel Intermediate: ROUND, ROUNDUP,  ROUNDDOWN Functions",
    "description": "In this tutorial, master three essential Excel rounding functions—ROUND, ROUNDUP, and ROUNDDOWN—that are crucial for ...",
    "publishedAt": "2025-08-21T10:00:53Z",
    "thumbnail": "https://i.ytimg.com/vi/Wg9z5jhVm5k/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "IfwzyF1Km0A",
    "title": "Excel Intermediate: RANK Function",
    "description": "In this tutorial, discover the power of Excel's RANK function for efficient data analysis and administrative task management in ...",
    "publishedAt": "2025-08-19T10:00:28Z",
    "thumbnail": "https://i.ytimg.com/vi/IfwzyF1Km0A/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "uYnVjXMWoBs",
    "title": "Pay and Entitlements: Basic Needs Allowance (BNA) - Application Submission Process",
    "description": "In this tutorial, learn the complete Basic Needs Allowance (BNA) application submission process through MOL MyEPAR, covering ...",
    "publishedAt": "2025-07-29T10:01:25Z",
    "thumbnail": "https://i.ytimg.com/vi/uYnVjXMWoBs/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "-tK3Sh1xePs",
    "title": "Pay and Entitlements: Basic Needs Allowance (BNA) - Eligibility Determination",
    "description": "In this tutorial, learn how to determine your Basic Needs Allowance (BNA) eligibility through the comprehensive assessment ...",
    "publishedAt": "2025-07-26T10:00:03Z",
    "thumbnail": "https://i.ytimg.com/vi/-tK3Sh1xePs/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Iu9T5bTJ0xw",
    "title": "Promotions: Understanding Selection Numbers",
    "description": "In this tutorial, learn how to effectively read and interpret Marine Corps promotion selection numbers through comprehensive ...",
    "publishedAt": "2025-07-03T10:00:37Z",
    "thumbnail": "https://i.ytimg.com/vi/Iu9T5bTJ0xw/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "NBtKCLp5lAg",
    "title": "Large Language Models: NIPR GPT - Create an account",
    "description": "In this tutorial, learn how to successfully create and configure a NIPR GPT account through the complete registration process, ...",
    "publishedAt": "2025-07-01T10:00:40Z",
    "thumbnail": "https://i.ytimg.com/vi/NBtKCLp5lAg/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Z_DFAO2u504",
    "title": "Manpower: Creating a TFSMS Account",
    "description": "In this tutorial, learn how to successfully create and configure a TFSMS (Total Force Structure Management System) account ...",
    "publishedAt": "2025-06-26T10:00:57Z",
    "thumbnail": "https://i.ytimg.com/vi/Z_DFAO2u504/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "oW0-yR7yZWg",
    "title": "Creating Correspondence: Naval Letter Format Generator",
    "description": "In this tutorial, learn how to efficiently use the Naval Letter Format Generator at https://marines.dev/navalletter/ to create ...",
    "publishedAt": "2025-06-25T00:28:23Z",
    "thumbnail": "https://i.ytimg.com/vi/oW0-yR7yZWg/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "HOQAX7Mc_-s",
    "title": "Improved Awards Processing System: Board Member - Understanding Your Role and Responsibilities",
    "description": "In this tutorial, learn the essential role and responsibilities of serving as an awards board member in the Improved Awards ...",
    "publishedAt": "2025-06-24T10:00:22Z",
    "thumbnail": "https://i.ytimg.com/vi/HOQAX7Mc_-s/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "d1ZrnYVTELs",
    "title": "Semper Admin: MISSO vs AAU vs MCAAT vs IGMC - What&#39;s the Difference?",
    "description": "In this tutorial, learn the critical differences between MISSO (Manpower Information Systems Support Office), AAU (Admin Assist ...",
    "publishedAt": "2025-06-19T10:01:10Z",
    "thumbnail": "https://i.ytimg.com/vi/d1ZrnYVTELs/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "yLf0XM2sxNQ",
    "title": "Tech Tips: Staying Current with Rapid Technology Changes",
    "description": "In this tutorial, learn essential strategies for staying current with rapid technology changes in today's software-as-a-service ...",
    "publishedAt": "2025-06-17T10:01:40Z",
    "thumbnail": "https://i.ytimg.com/vi/yLf0XM2sxNQ/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "j0pEbs5RIxI",
    "title": "Promotions: Understanding Promotion Zones",
    "description": "In this tutorial, learn how to effectively read and interpret Marine Corps promotion zone data to understand your current standing ...",
    "publishedAt": "2025-06-16T20:06:01Z",
    "thumbnail": "https://i.ytimg.com/vi/j0pEbs5RIxI/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "3tmcRvcfgW4",
    "title": "Large Language Models: Prompt Types - Zero-Shot vs Chain vs Mega",
    "description": "In this tutorial, learn the three essential prompt types for maximizing AI effectiveness in military administrative tasks: zero-shot ...",
    "publishedAt": "2025-06-14T10:00:06Z",
    "thumbnail": "https://i.ytimg.com/vi/3tmcRvcfgW4/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Qlc8zZ8Yzyk",
    "title": "Large Language Models: Prompt Components and Structure",
    "description": "In this tutorial, learn the essential components and structure needed to create highly effective AI prompts for military administrative ...",
    "publishedAt": "2025-06-12T10:00:44Z",
    "thumbnail": "https://i.ytimg.com/vi/Qlc8zZ8Yzyk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Rj9XfJuXI-U",
    "title": "Pay and Entitlements: Requesting IPCOT Travel",
    "description": "In this tutorial, learn the complete LOA submission process for approved IPCOT (In-Place Consecutive Overseas Tour) travel, ...",
    "publishedAt": "2025-06-10T20:12:01Z",
    "thumbnail": "https://i.ytimg.com/vi/Rj9XfJuXI-U/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "DBvVYFUDU4E",
    "title": "Large Language Models: BAMCIS Framework for Prompts",
    "description": "In this tutorial, learn how to apply the military BAMCIS framework to create highly effective AI prompts for administrative tasks.",
    "publishedAt": "2025-06-10T10:00:21Z",
    "thumbnail": "https://i.ytimg.com/vi/DBvVYFUDU4E/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "YtZUbyGtNs8",
    "title": "Large Language Models: Prompt Engineering Fundamentals",
    "description": "In this tutorial, I break down the essential prompt engineering techniques that every Marine needs to effectively communicate with ...",
    "publishedAt": "2025-06-07T10:00:50Z",
    "thumbnail": "https://i.ytimg.com/vi/YtZUbyGtNs8/default.jpg",
    "channelTitle": "Semper Admin"
  }
];

// Export for use in frontend (if using modules) or make globally available
if (typeof module !== 'undefined' && module.exports) {
  module.exports = YOUTUBE_VIDEOS;
}

// Make available globally for browser usage
if (typeof window !== 'undefined') {
  window.YOUTUBE_VIDEOS = YOUTUBE_VIDEOS;
}
